#--------------------------------------------------------------------------------
#             _______
#　　　　　 /  ＞　　フ     
#　　　　　| 　_　 _ l      THEME: abysal-obsidian
#　 　　　／` ミ＿xノ               
#　　 　 /　　　 　 |
#　　　 /　 ヽ　　 ﾉ
#　 　 │　　|　|　|         AUTHOR:  Andr3xDev
#　／￣|　　 |　|　|        URL: https://github.com/Andr3xDev/hypr-abysal
#　| (￣ヽ＿_ヽ_)__)
#　＼二つ
#--------------------------------------------------------------------------------


# Main background
theme[main_bg]="#0E161A"

# Main text color
theme[main_fg]="#E3E9EB"

# Title color for boxes
theme[title]="#E3E9EB"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#2DD4BF"

# Background color of selected items
theme[selected_bg]="#17393B"

# Foreground color of selected items
theme[selected_fg]="#2DD4BF"

# Color of inactive/disabled text
theme[inactive_fg]="#5B6E72"

# Color of text appearing on top of graphs
theme[graph_text]="#7A8B8E"

# Misc colors for processes box
theme[proc_misc]="#6C93E8"

# Cpu box outline color
theme[cpu_box]="#1D2C34"

# Memory/disks box outline color
theme[mem_box]="#1D2C34"

# Net up/down box outline color
theme[net_box]="#1D2C34"

# Processes box outline color
theme[proc_box]="#1D2C34"

# Box divider line and small boxes line color
theme[div_line]="#1D2C34"

# Temperature graph colors
theme[temp_start]="#6C93E8"
theme[temp_mid]="#E9D568"
theme[temp_end]="#FF8352"

# CPU graph colors
theme[cpu_start]="#2DD4BF"
theme[cpu_mid]="#D9973A"
theme[cpu_end]="#FF8352"

# Mem/Disk free meter
theme[free_start]="#2DD4BF"
theme[free_mid]=""
theme[free_end]=""

# Mem/Disk cached meter
theme[cached_start]="#D9973A"
theme[cached_mid]=""
theme[cached_end]=""

# Mem/Disk available meter
theme[available_start]="#2DD4BF"
theme[available_mid]=""
theme[available_end]=""

# Mem/Disk used meter
theme[used_start]="#FF8352"
theme[used_mid]=""
theme[used_end]=""

# Download graph colors
theme[download_start]="#E9D568"
theme[download_mid]="#D9973A"
theme[download_end]="#FF8352""

# Upload graph colors
theme[upload_start]="#D9973A"
theme[upload_mid]="#E9D568"
theme[upload_end]="#6EB99A"
