# ---------------------------------------------------------------------------
# Abysal Obsidian
# Color palette and UI tokens for the Abysal Obsidian theme
# ---------------------------------------------------------------------------

$base    = rgb(0e161a) # main_background
$surface = rgb(152025) # secondary_background
$text    = rgb(e3e9eb) # main_text

$color1 = rgb(2dd4bf) # turquoise
$color2 = rgb(d9973a) # orange
$color3 = rgb(e9d568) # sand
$color4 = rgb(ff6369) # soft_red
$color5 = rgb(6c93e8) # steel_blue
$color6 = rgb(ab8ab7) # lavender_purple
$color7 = rgb(7a8b8e) # light_gray_secondary
$color8 = rgb(5b6e72) # medium_gray_comments
$color9 = rgb(1d2c34) # dark_gray_borders

# Highlight colors
$highlight1 = rgb(152025) # faint_selection
$highlight2 = rgb(324a54) # medium_selection
$highlight3 = rgb(516e7a) # strong_selection

$wallpaper = ~/.config/wallpapers/tkg.jpg

# Border configuration
$border_active   = rgb(1d2c34) # Gray focus (Highlight 3)
$border_inactive = rgb(19262c)     # Darker gray borders
$border_urgent   = $color4     # Soft Red

$opacity = 0.95

# Hyprlock Specifics
$lock_background_brightness = 0.8

$lock_backsurface = rgba(14, 22, 26, 0.95)
$lock_border_color = rgba(50, 74, 84, 1)

$lock_text          = $text
$lock_shadow        = $base

$lock_time_hours    = $text
$lock_time_date     = $color2

$lock_input_bg      = $surface
$lock_input_border  = $color1
$lock_input_text    = $text

$lock_actions_border = $color1
$lock_actions_text  = $text

$lock_battery_bg    = $surface
$lock_battery_border = $color1
$lock_battery_text  = $text
